
services:
  db:
    image: mongo:7.0.15
    environment:
      MONGO_INITDB_DATABASE: marketplace_db  # Name of your default database
    volumes:
      - ./data/mongodb:/data/db  # MongoDB data persistence
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro  # Initialization script
    ports:
      - "27017:27017"  # Expose MongoDB to localhost
  
  api:
    image: api
    build:
      context: .
      dockerfile: docker/api.Dockerfile
    ports:
      - "9001:9001"
    healthcheck:
      test: 'curl --fail http://localhost:9001/graphql?query=%7B__typename%7D -H "Content-Type: application/json"  || exit 1'
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 3s
    env_file: .env


  processor:
    image: processor
    build:
      context: .
      dockerfile: docker/processor.Dockerfile
    env_file: .env
    ports:
      - "3005:3005"

  fetcher:
    image: fetcher
    build:
      context: .
      dockerfile: docker/fetcher.Dockerfile
    env_file: .env
  
  ui:
    image: ui
    depends_on: 
      api:
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    ports:
      - "3000:3000"
    env_file: .env
